package com.anterp.mybatis.mapper;

import com.anterp.mybatis.domain.Account;
import com.anterp.mybatis.domain.AccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int countByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int deleteByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int deleteByPrimaryKey(Integer accid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    List<Account> selectByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    Account selectByPrimaryKey(Integer accid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int updateByExampleSelective(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int updateByExample(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int updateByPrimaryKey(Account record);
}