package com.anterp.mybatis.mapper;

import com.anterp.mybatis.domain.AccountRole;
import com.anterp.mybatis.domain.AccountRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_acc_role
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int countByExample(AccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_acc_role
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int deleteByExample(AccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_acc_role
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int insert(AccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_acc_role
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int insertSelective(AccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_acc_role
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    List<AccountRole> selectByExample(AccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_acc_role
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int updateByExampleSelective(@Param("record") AccountRole record, @Param("example") AccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_acc_role
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int updateByExample(@Param("record") AccountRole record, @Param("example") AccountRoleExample example);
}