package com.anterp.mybatis.mapper;

import com.anterp.mybatis.domain.Custom;
import com.anterp.mybatis.domain.CustomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_custom
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int countByExample(CustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_custom
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int deleteByExample(CustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_custom
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int deleteByPrimaryKey(Integer custid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_custom
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int insert(Custom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_custom
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int insertSelective(Custom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_custom
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    List<Custom> selectByExample(CustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_custom
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    Custom selectByPrimaryKey(Integer custid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_custom
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int updateByExampleSelective(@Param("record") Custom record, @Param("example") CustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_custom
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int updateByExample(@Param("record") Custom record, @Param("example") CustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_custom
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int updateByPrimaryKeySelective(Custom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_custom
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    int updateByPrimaryKey(Custom record);
}