package com.anterp.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class Account implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.accId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Integer accid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.empName
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private String empname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.accName
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private String accname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.accPwd
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private String accpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.age
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.gender
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Short gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.phoneNo
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private String phoneno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.urgentPhone
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private String urgentphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.address
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.createTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.lastModifyTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Date lastmodifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_account
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.accId
     *
     * @return the value of tbl_account.accId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Integer getAccid() {
        return accid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.accId
     *
     * @param accid the value for tbl_account.accId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setAccid(Integer accid) {
        this.accid = accid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.empName
     *
     * @return the value of tbl_account.empName
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public String getEmpname() {
        return empname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.empName
     *
     * @param empname the value for tbl_account.empName
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setEmpname(String empname) {
        this.empname = empname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.accName
     *
     * @return the value of tbl_account.accName
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public String getAccname() {
        return accname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.accName
     *
     * @param accname the value for tbl_account.accName
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setAccname(String accname) {
        this.accname = accname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.accPwd
     *
     * @return the value of tbl_account.accPwd
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public String getAccpwd() {
        return accpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.accPwd
     *
     * @param accpwd the value for tbl_account.accPwd
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setAccpwd(String accpwd) {
        this.accpwd = accpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.age
     *
     * @return the value of tbl_account.age
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.age
     *
     * @param age the value for tbl_account.age
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.gender
     *
     * @return the value of tbl_account.gender
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Short getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.gender
     *
     * @param gender the value for tbl_account.gender
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setGender(Short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.phoneNo
     *
     * @return the value of tbl_account.phoneNo
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public String getPhoneno() {
        return phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.phoneNo
     *
     * @param phoneno the value for tbl_account.phoneNo
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.urgentPhone
     *
     * @return the value of tbl_account.urgentPhone
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public String getUrgentphone() {
        return urgentphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.urgentPhone
     *
     * @param urgentphone the value for tbl_account.urgentPhone
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setUrgentphone(String urgentphone) {
        this.urgentphone = urgentphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.address
     *
     * @return the value of tbl_account.address
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.address
     *
     * @param address the value for tbl_account.address
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.createTime
     *
     * @return the value of tbl_account.createTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.createTime
     *
     * @param createtime the value for tbl_account.createTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.lastModifyTime
     *
     * @return the value of tbl_account.lastModifyTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Date getLastmodifytime() {
        return lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.lastModifyTime
     *
     * @param lastmodifytime the value for tbl_account.lastModifyTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setLastmodifytime(Date lastmodifytime) {
        this.lastmodifytime = lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Account other = (Account) that;
        return (this.getAccid() == null ? other.getAccid() == null : this.getAccid().equals(other.getAccid()))
            && (this.getEmpname() == null ? other.getEmpname() == null : this.getEmpname().equals(other.getEmpname()))
            && (this.getAccname() == null ? other.getAccname() == null : this.getAccname().equals(other.getAccname()))
            && (this.getAccpwd() == null ? other.getAccpwd() == null : this.getAccpwd().equals(other.getAccpwd()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getPhoneno() == null ? other.getPhoneno() == null : this.getPhoneno().equals(other.getPhoneno()))
            && (this.getUrgentphone() == null ? other.getUrgentphone() == null : this.getUrgentphone().equals(other.getUrgentphone()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getLastmodifytime() == null ? other.getLastmodifytime() == null : this.getLastmodifytime().equals(other.getLastmodifytime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAccid() == null) ? 0 : getAccid().hashCode());
        result = prime * result + ((getEmpname() == null) ? 0 : getEmpname().hashCode());
        result = prime * result + ((getAccname() == null) ? 0 : getAccname().hashCode());
        result = prime * result + ((getAccpwd() == null) ? 0 : getAccpwd().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getPhoneno() == null) ? 0 : getPhoneno().hashCode());
        result = prime * result + ((getUrgentphone() == null) ? 0 : getUrgentphone().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getLastmodifytime() == null) ? 0 : getLastmodifytime().hashCode());
        return result;
    }
}