package com.anterp.mybatis.domain;

import java.io.Serializable;

public class AccountRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_acc_role.accId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Integer accid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_acc_role.roleId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_acc_role
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_acc_role.accId
     *
     * @return the value of tbl_acc_role.accId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Integer getAccid() {
        return accid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_acc_role.accId
     *
     * @param accid the value for tbl_acc_role.accId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setAccid(Integer accid) {
        this.accid = accid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_acc_role.roleId
     *
     * @return the value of tbl_acc_role.roleId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_acc_role.roleId
     *
     * @param roleid the value for tbl_acc_role.roleId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_acc_role
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AccountRole other = (AccountRole) that;
        return (this.getAccid() == null ? other.getAccid() == null : this.getAccid().equals(other.getAccid()))
            && (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_acc_role
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAccid() == null) ? 0 : getAccid().hashCode());
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        return result;
    }
}