package com.anterp.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class Custom implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_custom.custId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Integer custid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_custom.custName
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private String custname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_custom.gender
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Short gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_custom.age
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_custom.birthday
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_custom.phoneNo
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private String phoneno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_custom.address
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_custom.familyDesc
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private String familydesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_custom.createTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_custom.lastModifyTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Date lastmodifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_custom
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_custom.custId
     *
     * @return the value of tbl_custom.custId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Integer getCustid() {
        return custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_custom.custId
     *
     * @param custid the value for tbl_custom.custId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setCustid(Integer custid) {
        this.custid = custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_custom.custName
     *
     * @return the value of tbl_custom.custName
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_custom.custName
     *
     * @param custname the value for tbl_custom.custName
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setCustname(String custname) {
        this.custname = custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_custom.gender
     *
     * @return the value of tbl_custom.gender
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Short getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_custom.gender
     *
     * @param gender the value for tbl_custom.gender
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setGender(Short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_custom.age
     *
     * @return the value of tbl_custom.age
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_custom.age
     *
     * @param age the value for tbl_custom.age
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_custom.birthday
     *
     * @return the value of tbl_custom.birthday
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_custom.birthday
     *
     * @param birthday the value for tbl_custom.birthday
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_custom.phoneNo
     *
     * @return the value of tbl_custom.phoneNo
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public String getPhoneno() {
        return phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_custom.phoneNo
     *
     * @param phoneno the value for tbl_custom.phoneNo
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_custom.address
     *
     * @return the value of tbl_custom.address
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_custom.address
     *
     * @param address the value for tbl_custom.address
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_custom.familyDesc
     *
     * @return the value of tbl_custom.familyDesc
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public String getFamilydesc() {
        return familydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_custom.familyDesc
     *
     * @param familydesc the value for tbl_custom.familyDesc
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setFamilydesc(String familydesc) {
        this.familydesc = familydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_custom.createTime
     *
     * @return the value of tbl_custom.createTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_custom.createTime
     *
     * @param createtime the value for tbl_custom.createTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_custom.lastModifyTime
     *
     * @return the value of tbl_custom.lastModifyTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Date getLastmodifytime() {
        return lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_custom.lastModifyTime
     *
     * @param lastmodifytime the value for tbl_custom.lastModifyTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setLastmodifytime(Date lastmodifytime) {
        this.lastmodifytime = lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_custom
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Custom other = (Custom) that;
        return (this.getCustid() == null ? other.getCustid() == null : this.getCustid().equals(other.getCustid()))
            && (this.getCustname() == null ? other.getCustname() == null : this.getCustname().equals(other.getCustname()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getPhoneno() == null ? other.getPhoneno() == null : this.getPhoneno().equals(other.getPhoneno()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getFamilydesc() == null ? other.getFamilydesc() == null : this.getFamilydesc().equals(other.getFamilydesc()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getLastmodifytime() == null ? other.getLastmodifytime() == null : this.getLastmodifytime().equals(other.getLastmodifytime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_custom
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCustid() == null) ? 0 : getCustid().hashCode());
        result = prime * result + ((getCustname() == null) ? 0 : getCustname().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getPhoneno() == null) ? 0 : getPhoneno().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getFamilydesc() == null) ? 0 : getFamilydesc().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getLastmodifytime() == null) ? 0 : getLastmodifytime().hashCode());
        return result;
    }
}