package com.anterp.mybatis.domain;

import java.io.Serializable;

public class Privilege implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role_pvg.roleId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role_pvg.pvgId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private String pvgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_role_pvg
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role_pvg.roleId
     *
     * @return the value of tbl_role_pvg.roleId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role_pvg.roleId
     *
     * @param roleid the value for tbl_role_pvg.roleId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role_pvg.pvgId
     *
     * @return the value of tbl_role_pvg.pvgId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public String getPvgid() {
        return pvgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role_pvg.pvgId
     *
     * @param pvgid the value for tbl_role_pvg.pvgId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setPvgid(String pvgid) {
        this.pvgid = pvgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_pvg
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Privilege other = (Privilege) that;
        return (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()))
            && (this.getPvgid() == null ? other.getPvgid() == null : this.getPvgid().equals(other.getPvgid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role_pvg
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        result = prime * result + ((getPvgid() == null) ? 0 : getPvgid().hashCode());
        return result;
    }
}