package com.anterp.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class Role implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role.roleId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role.roleName
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role.description
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role.createTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role.lastModifyTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private Date lastmodifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_role
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role.roleId
     *
     * @return the value of tbl_role.roleId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role.roleId
     *
     * @param roleid the value for tbl_role.roleId
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role.roleName
     *
     * @return the value of tbl_role.roleName
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role.roleName
     *
     * @param rolename the value for tbl_role.roleName
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role.description
     *
     * @return the value of tbl_role.description
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role.description
     *
     * @param description the value for tbl_role.description
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role.createTime
     *
     * @return the value of tbl_role.createTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role.createTime
     *
     * @param createtime the value for tbl_role.createTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role.lastModifyTime
     *
     * @return the value of tbl_role.lastModifyTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public Date getLastmodifytime() {
        return lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role.lastModifyTime
     *
     * @param lastmodifytime the value for tbl_role.lastModifyTime
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    public void setLastmodifytime(Date lastmodifytime) {
        this.lastmodifytime = lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Role other = (Role) that;
        return (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()))
            && (this.getRolename() == null ? other.getRolename() == null : this.getRolename().equals(other.getRolename()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getLastmodifytime() == null ? other.getLastmodifytime() == null : this.getLastmodifytime().equals(other.getLastmodifytime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbggenerated Sat Apr 21 15:40:10 CST 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        result = prime * result + ((getRolename() == null) ? 0 : getRolename().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getLastmodifytime() == null) ? 0 : getLastmodifytime().hashCode());
        return result;
    }
}